

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"
use_frameworks!

target 'sound_app' do
  # pod 'CVCalendar', '~> 1.2.9'
  pod 'AFNetworking', "3.0.4"
  pod 'Alamofire', '~> 4.0'
  # pod 'SwiftyJSON', '3.0.0'
  #
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
